// Auto-generated by scripts/generate-photo-data.ts
// Run: npm run photos
//
// Configure gallery highlights and collection covers in public/photos/config.json

export interface Photo {
  id: string
  src: string
  alt: string
  collection?: string
  featured?: boolean
}

export interface Collection {
  id: string
  title: string
  description?: string
  coverPhoto: string
  category?: string
}

export const collections: Collection[] = [
  {
    "id": "julia-+-jenna",
    "title": "Julia + Jenna",
    "description": "Mini session in Tigard, Oregon",
    "category": "People",
    "coverPhoto": "/photos/julia-+-jenna/original%202026-05-07%20215050E3414A69DD01.jpg"
  },
  {
    "id": "meaca",
    "title": "Meaca",
    "description": "Graduation shoot at Oregon State University",
    "category": "People",
    "coverPhoto": "/photos/meaca/original%202026-05-18%20155950B6A9F4A59A0E.jpg"
  },
  {
    "id": "missio",
    "title": "Missio",
    "description": "Moments from Missio Community Church",
    "category": "Moments",
    "coverPhoto": "/photos/missio/original%202026-06-07%20175511246B5A906282.JPG"
  },
  {
    "id": "shreya",
    "title": "Shreya",
    "description": "Mini session at Nike World Headquarters",
    "category": "People",
    "coverPhoto": "/photos/shreya/SCRL_0082.jpg"
  },
  {
    "id": "tiana",
    "title": "Tiana",
    "description": "Mini session in Corvallis, Oregon",
    "category": "People",
    "coverPhoto": "/photos/tiana/original%202026-04-28%2014592082B001FD61D1.JPG"
  }
]

export const photos: Photo[] = [
  {
    "id": "meaca/original 2026-05-18 155512C99A597D9BB8.jpg",
    "src": "/photos/meaca/original%202026-05-18%20155512C99A597D9BB8.jpg",
    "alt": "original 2026 05 18 155512C99A597D9BB8",
    "collection": "meaca",
    "featured": true
  },
  {
    "id": "meaca/original 2026-05-18 1555533565664C3254.jpg",
    "src": "/photos/meaca/original%202026-05-18%201555533565664C3254.jpg",
    "alt": "original 2026 05 18 1555533565664C3254",
    "collection": "meaca",
    "featured": true
  },
  {
    "id": "meaca/original 2026-05-18 155555A82C487BBB57.jpg",
    "src": "/photos/meaca/original%202026-05-18%20155555A82C487BBB57.jpg",
    "alt": "original 2026 05 18 155555A82C487BBB57",
    "collection": "meaca",
    "featured": true
  },
  {
    "id": "shreya/SCRL_0067.jpg",
    "src": "/photos/shreya/SCRL_0067.jpg",
    "alt": "SCRL 0067",
    "collection": "shreya",
    "featured": true
  },
  {
    "id": "shreya/SCRL_0068.jpg",
    "src": "/photos/shreya/SCRL_0068.jpg",
    "alt": "SCRL 0068",
    "collection": "shreya",
    "featured": true
  },
  {
    "id": "shreya/SCRL_0069.jpg",
    "src": "/photos/shreya/SCRL_0069.jpg",
    "alt": "SCRL 0069",
    "collection": "shreya",
    "featured": true
  },
  {
    "id": "julia-+-jenna/original 2026-05-07 214649C5D30A8978C5.jpg",
    "src": "/photos/julia-+-jenna/original%202026-05-07%20214649C5D30A8978C5.jpg",
    "alt": "original 2026 05 07 214649C5D30A8978C5",
    "collection": "julia-+-jenna",
    "featured": true
  },
  {
    "id": "julia-+-jenna/original 2026-05-07 214729E0537CDD4FB0.JPG",
    "src": "/photos/julia-+-jenna/original%202026-05-07%20214729E0537CDD4FB0.JPG",
    "alt": "original 2026 05 07 214729E0537CDD4FB0",
    "collection": "julia-+-jenna",
    "featured": true
  },
  {
    "id": "julia-+-jenna/original 2026-05-07 214730CB70999798F4.jpg",
    "src": "/photos/julia-+-jenna/original%202026-05-07%20214730CB70999798F4.jpg",
    "alt": "original 2026 05 07 214730CB70999798F4",
    "collection": "julia-+-jenna",
    "featured": true
  },
  {
    "id": "tiana/original 2026-04-28 145822CD5B52B72864.JPG",
    "src": "/photos/tiana/original%202026-04-28%20145822CD5B52B72864.JPG",
    "alt": "original 2026 04 28 145822CD5B52B72864",
    "collection": "tiana",
    "featured": true
  },
  {
    "id": "tiana/original 2026-04-28 1458265C215EE54EA5.JPG",
    "src": "/photos/tiana/original%202026-04-28%201458265C215EE54EA5.JPG",
    "alt": "original 2026 04 28 1458265C215EE54EA5",
    "collection": "tiana",
    "featured": true
  },
  {
    "id": "tiana/original 2026-04-28 145827830E6E79C38C.JPG",
    "src": "/photos/tiana/original%202026-04-28%20145827830E6E79C38C.JPG",
    "alt": "original 2026 04 28 145827830E6E79C38C",
    "collection": "tiana",
    "featured": true
  },
  {
    "id": "missio/original 2026-06-07 175406973C583A9F48.JPG",
    "src": "/photos/missio/original%202026-06-07%20175406973C583A9F48.JPG",
    "alt": "original 2026 06 07 175406973C583A9F48",
    "collection": "missio",
    "featured": true
  },
  {
    "id": "missio/original 2026-06-07 17541026694E5FAB3A.JPG",
    "src": "/photos/missio/original%202026-06-07%2017541026694E5FAB3A.JPG",
    "alt": "original 2026 06 07 17541026694E5FAB3A",
    "collection": "missio",
    "featured": true
  },
  {
    "id": "missio/original 2026-06-07 175410E12EB9A01A1D.JPG",
    "src": "/photos/missio/original%202026-06-07%20175410E12EB9A01A1D.JPG",
    "alt": "original 2026 06 07 175410E12EB9A01A1D",
    "collection": "missio",
    "featured": true
  },
  {
    "id": "julia-+-jenna/original 2026-05-07 2149094A5703F4A25D.jpg",
    "src": "/photos/julia-+-jenna/original%202026-05-07%202149094A5703F4A25D.jpg",
    "alt": "original 2026 05 07 2149094A5703F4A25D",
    "collection": "julia-+-jenna",
    "featured": false
  },
  {
    "id": "julia-+-jenna/original 2026-05-07 2149501BDD2074A75F.JPG",
    "src": "/photos/julia-+-jenna/original%202026-05-07%202149501BDD2074A75F.JPG",
    "alt": "original 2026 05 07 2149501BDD2074A75F",
    "collection": "julia-+-jenna",
    "featured": false
  },
  {
    "id": "julia-+-jenna/original 2026-05-07 215006F22E06C88E83.JPG",
    "src": "/photos/julia-+-jenna/original%202026-05-07%20215006F22E06C88E83.JPG",
    "alt": "original 2026 05 07 215006F22E06C88E83",
    "collection": "julia-+-jenna",
    "featured": false
  },
  {
    "id": "julia-+-jenna/original 2026-05-07 2150407D0A637F3D8B.jpg",
    "src": "/photos/julia-+-jenna/original%202026-05-07%202150407D0A637F3D8B.jpg",
    "alt": "original 2026 05 07 2150407D0A637F3D8B",
    "collection": "julia-+-jenna",
    "featured": false
  },
  {
    "id": "julia-+-jenna/original 2026-05-07 215043B9F5AED8CFC3.jpg",
    "src": "/photos/julia-+-jenna/original%202026-05-07%20215043B9F5AED8CFC3.jpg",
    "alt": "original 2026 05 07 215043B9F5AED8CFC3",
    "collection": "julia-+-jenna",
    "featured": false
  },
  {
    "id": "julia-+-jenna/original 2026-05-07 215050E3414A69DD01.jpg",
    "src": "/photos/julia-+-jenna/original%202026-05-07%20215050E3414A69DD01.jpg",
    "alt": "original 2026 05 07 215050E3414A69DD01",
    "collection": "julia-+-jenna",
    "featured": false
  },
  {
    "id": "julia-+-jenna/original 2026-05-07 2150554B6126C4EFCE.jpg",
    "src": "/photos/julia-+-jenna/original%202026-05-07%202150554B6126C4EFCE.jpg",
    "alt": "original 2026 05 07 2150554B6126C4EFCE",
    "collection": "julia-+-jenna",
    "featured": false
  },
  {
    "id": "julia-+-jenna/original 2026-05-07 2151054933DAE49CE9.jpg",
    "src": "/photos/julia-+-jenna/original%202026-05-07%202151054933DAE49CE9.jpg",
    "alt": "original 2026 05 07 2151054933DAE49CE9",
    "collection": "julia-+-jenna",
    "featured": false
  },
  {
    "id": "julia-+-jenna/original 2026-05-07 2151081653BF7CA8B3.JPG",
    "src": "/photos/julia-+-jenna/original%202026-05-07%202151081653BF7CA8B3.JPG",
    "alt": "original 2026 05 07 2151081653BF7CA8B3",
    "collection": "julia-+-jenna",
    "featured": false
  },
  {
    "id": "julia-+-jenna/original 2026-05-07 2152106C3214074277.jpg",
    "src": "/photos/julia-+-jenna/original%202026-05-07%202152106C3214074277.jpg",
    "alt": "original 2026 05 07 2152106C3214074277",
    "collection": "julia-+-jenna",
    "featured": false
  },
  {
    "id": "julia-+-jenna/original 2026-05-07 2152332EA661AD1D3B.jpg",
    "src": "/photos/julia-+-jenna/original%202026-05-07%202152332EA661AD1D3B.jpg",
    "alt": "original 2026 05 07 2152332EA661AD1D3B",
    "collection": "julia-+-jenna",
    "featured": false
  },
  {
    "id": "julia-+-jenna/original 2026-05-07 215342DE2638D07D53.jpg",
    "src": "/photos/julia-+-jenna/original%202026-05-07%20215342DE2638D07D53.jpg",
    "alt": "original 2026 05 07 215342DE2638D07D53",
    "collection": "julia-+-jenna",
    "featured": false
  },
  {
    "id": "julia-+-jenna/original 2026-05-07 215409E42E5AFE3944.jpg",
    "src": "/photos/julia-+-jenna/original%202026-05-07%20215409E42E5AFE3944.jpg",
    "alt": "original 2026 05 07 215409E42E5AFE3944",
    "collection": "julia-+-jenna",
    "featured": false
  },
  {
    "id": "julia-+-jenna/original 2026-05-07 21541286E9904FC631.jpg",
    "src": "/photos/julia-+-jenna/original%202026-05-07%2021541286E9904FC631.jpg",
    "alt": "original 2026 05 07 21541286E9904FC631",
    "collection": "julia-+-jenna",
    "featured": false
  },
  {
    "id": "julia-+-jenna/original 2026-05-07 215558D749B1E2D426.jpg",
    "src": "/photos/julia-+-jenna/original%202026-05-07%20215558D749B1E2D426.jpg",
    "alt": "original 2026 05 07 215558D749B1E2D426",
    "collection": "julia-+-jenna",
    "featured": false
  },
  {
    "id": "julia-+-jenna/original 2026-05-07 2156012D7CABA810D9.jpg",
    "src": "/photos/julia-+-jenna/original%202026-05-07%202156012D7CABA810D9.jpg",
    "alt": "original 2026 05 07 2156012D7CABA810D9",
    "collection": "julia-+-jenna",
    "featured": false
  },
  {
    "id": "meaca/original 2026-05-18 155606D7611E8B1CA2.jpg",
    "src": "/photos/meaca/original%202026-05-18%20155606D7611E8B1CA2.jpg",
    "alt": "original 2026 05 18 155606D7611E8B1CA2",
    "collection": "meaca",
    "featured": false
  },
  {
    "id": "meaca/original 2026-05-18 155834C55CA156D1F0.jpg",
    "src": "/photos/meaca/original%202026-05-18%20155834C55CA156D1F0.jpg",
    "alt": "original 2026 05 18 155834C55CA156D1F0",
    "collection": "meaca",
    "featured": false
  },
  {
    "id": "meaca/original 2026-05-18 155950B6A9F4A59A0E.jpg",
    "src": "/photos/meaca/original%202026-05-18%20155950B6A9F4A59A0E.jpg",
    "alt": "original 2026 05 18 155950B6A9F4A59A0E",
    "collection": "meaca",
    "featured": false
  },
  {
    "id": "meaca/original 2026-05-18 160006F430B517356C.jpg",
    "src": "/photos/meaca/original%202026-05-18%20160006F430B517356C.jpg",
    "alt": "original 2026 05 18 160006F430B517356C",
    "collection": "meaca",
    "featured": false
  },
  {
    "id": "meaca/original 2026-05-18 160146D4F8432D45B1.JPG",
    "src": "/photos/meaca/original%202026-05-18%20160146D4F8432D45B1.JPG",
    "alt": "original 2026 05 18 160146D4F8432D45B1",
    "collection": "meaca",
    "featured": false
  },
  {
    "id": "meaca/original 2026-05-18 160210FEFBE4433A7E.JPG",
    "src": "/photos/meaca/original%202026-05-18%20160210FEFBE4433A7E.JPG",
    "alt": "original 2026 05 18 160210FEFBE4433A7E",
    "collection": "meaca",
    "featured": false
  },
  {
    "id": "meaca/original 2026-05-18 1603077ABBA21B0C08.JPG",
    "src": "/photos/meaca/original%202026-05-18%201603077ABBA21B0C08.JPG",
    "alt": "original 2026 05 18 1603077ABBA21B0C08",
    "collection": "meaca",
    "featured": false
  },
  {
    "id": "meaca/original 2026-05-18 160310B3E972F612F8.jpg",
    "src": "/photos/meaca/original%202026-05-18%20160310B3E972F612F8.jpg",
    "alt": "original 2026 05 18 160310B3E972F612F8",
    "collection": "meaca",
    "featured": false
  },
  {
    "id": "meaca/original 2026-05-18 16051643FA822C9F9C.jpg",
    "src": "/photos/meaca/original%202026-05-18%2016051643FA822C9F9C.jpg",
    "alt": "original 2026 05 18 16051643FA822C9F9C",
    "collection": "meaca",
    "featured": false
  },
  {
    "id": "meaca/original 2026-05-18 1606208ABFE808EA27.JPG",
    "src": "/photos/meaca/original%202026-05-18%201606208ABFE808EA27.JPG",
    "alt": "original 2026 05 18 1606208ABFE808EA27",
    "collection": "meaca",
    "featured": false
  },
  {
    "id": "meaca/original 2026-05-18 16064543A7C2393665.jpg",
    "src": "/photos/meaca/original%202026-05-18%2016064543A7C2393665.jpg",
    "alt": "original 2026 05 18 16064543A7C2393665",
    "collection": "meaca",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 175411E010DB41BE84.JPG",
    "src": "/photos/missio/original%202026-06-07%20175411E010DB41BE84.JPG",
    "alt": "original 2026 06 07 175411E010DB41BE84",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 175412BA34FEC089FD.JPG",
    "src": "/photos/missio/original%202026-06-07%20175412BA34FEC089FD.JPG",
    "alt": "original 2026 06 07 175412BA34FEC089FD",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 175426D9F5548B27B1.JPG",
    "src": "/photos/missio/original%202026-06-07%20175426D9F5548B27B1.JPG",
    "alt": "original 2026 06 07 175426D9F5548B27B1",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 1754275B8C407B340F.JPG",
    "src": "/photos/missio/original%202026-06-07%201754275B8C407B340F.JPG",
    "alt": "original 2026 06 07 1754275B8C407B340F",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 1754283FA4BD6C28D0.JPG",
    "src": "/photos/missio/original%202026-06-07%201754283FA4BD6C28D0.JPG",
    "alt": "original 2026 06 07 1754283FA4BD6C28D0",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 1754293DF4827F86C3.JPG",
    "src": "/photos/missio/original%202026-06-07%201754293DF4827F86C3.JPG",
    "alt": "original 2026 06 07 1754293DF4827F86C3",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 1754304AFE11D44991.JPG",
    "src": "/photos/missio/original%202026-06-07%201754304AFE11D44991.JPG",
    "alt": "original 2026 06 07 1754304AFE11D44991",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 1754372BBE40547E8E.JPG",
    "src": "/photos/missio/original%202026-06-07%201754372BBE40547E8E.JPG",
    "alt": "original 2026 06 07 1754372BBE40547E8E",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 175439BE7CB4D6C3AF.JPG",
    "src": "/photos/missio/original%202026-06-07%20175439BE7CB4D6C3AF.JPG",
    "alt": "original 2026 06 07 175439BE7CB4D6C3AF",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 175440932A1E41A6F5.JPG",
    "src": "/photos/missio/original%202026-06-07%20175440932A1E41A6F5.JPG",
    "alt": "original 2026 06 07 175440932A1E41A6F5",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 175441C06D9F2CD7AF.JPG",
    "src": "/photos/missio/original%202026-06-07%20175441C06D9F2CD7AF.JPG",
    "alt": "original 2026 06 07 175441C06D9F2CD7AF",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 17544205C390767160.JPG",
    "src": "/photos/missio/original%202026-06-07%2017544205C390767160.JPG",
    "alt": "original 2026 06 07 17544205C390767160",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 175444376868ECA839.JPG",
    "src": "/photos/missio/original%202026-06-07%20175444376868ECA839.JPG",
    "alt": "original 2026 06 07 175444376868ECA839",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 1754447862A92FF20A.JPG",
    "src": "/photos/missio/original%202026-06-07%201754447862A92FF20A.JPG",
    "alt": "original 2026 06 07 1754447862A92FF20A",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 175455E8C3034573A9.JPG",
    "src": "/photos/missio/original%202026-06-07%20175455E8C3034573A9.JPG",
    "alt": "original 2026 06 07 175455E8C3034573A9",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 175457D82A5EB6C477.JPG",
    "src": "/photos/missio/original%202026-06-07%20175457D82A5EB6C477.JPG",
    "alt": "original 2026 06 07 175457D82A5EB6C477",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 17545895865B9A7C3C.JPG",
    "src": "/photos/missio/original%202026-06-07%2017545895865B9A7C3C.JPG",
    "alt": "original 2026 06 07 17545895865B9A7C3C",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 175459BF1A36B9C2EA.JPG",
    "src": "/photos/missio/original%202026-06-07%20175459BF1A36B9C2EA.JPG",
    "alt": "original 2026 06 07 175459BF1A36B9C2EA",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 175510CADAF8FF896F.JPG",
    "src": "/photos/missio/original%202026-06-07%20175510CADAF8FF896F.JPG",
    "alt": "original 2026 06 07 175510CADAF8FF896F",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 175511246B5A906282.JPG",
    "src": "/photos/missio/original%202026-06-07%20175511246B5A906282.JPG",
    "alt": "original 2026 06 07 175511246B5A906282",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 1755125346183D63D3.JPG",
    "src": "/photos/missio/original%202026-06-07%201755125346183D63D3.JPG",
    "alt": "original 2026 06 07 1755125346183D63D3",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 175513E1CBD13A7925.JPG",
    "src": "/photos/missio/original%202026-06-07%20175513E1CBD13A7925.JPG",
    "alt": "original 2026 06 07 175513E1CBD13A7925",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 1755154D167A983B7B.JPG",
    "src": "/photos/missio/original%202026-06-07%201755154D167A983B7B.JPG",
    "alt": "original 2026 06 07 1755154D167A983B7B",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 175515BC6F64F984B6.JPG",
    "src": "/photos/missio/original%202026-06-07%20175515BC6F64F984B6.JPG",
    "alt": "original 2026 06 07 175515BC6F64F984B6",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 175516B71B335F97A1.JPG",
    "src": "/photos/missio/original%202026-06-07%20175516B71B335F97A1.JPG",
    "alt": "original 2026 06 07 175516B71B335F97A1",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 175523B2A4C0FD4C30.JPG",
    "src": "/photos/missio/original%202026-06-07%20175523B2A4C0FD4C30.JPG",
    "alt": "original 2026 06 07 175523B2A4C0FD4C30",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "missio/original 2026-06-07 1755271CE6BA85B1AE.JPG",
    "src": "/photos/missio/original%202026-06-07%201755271CE6BA85B1AE.JPG",
    "alt": "original 2026 06 07 1755271CE6BA85B1AE",
    "collection": "missio",
    "featured": false
  },
  {
    "id": "shreya/SCRL_0070.jpg",
    "src": "/photos/shreya/SCRL_0070.jpg",
    "alt": "SCRL 0070",
    "collection": "shreya",
    "featured": false
  },
  {
    "id": "shreya/SCRL_0071.jpg",
    "src": "/photos/shreya/SCRL_0071.jpg",
    "alt": "SCRL 0071",
    "collection": "shreya",
    "featured": false
  },
  {
    "id": "shreya/SCRL_0072.jpg",
    "src": "/photos/shreya/SCRL_0072.jpg",
    "alt": "SCRL 0072",
    "collection": "shreya",
    "featured": false
  },
  {
    "id": "shreya/SCRL_0078.jpg",
    "src": "/photos/shreya/SCRL_0078.jpg",
    "alt": "SCRL 0078",
    "collection": "shreya",
    "featured": false
  },
  {
    "id": "shreya/SCRL_0080.jpg",
    "src": "/photos/shreya/SCRL_0080.jpg",
    "alt": "SCRL 0080",
    "collection": "shreya",
    "featured": false
  },
  {
    "id": "shreya/SCRL_0082.jpg",
    "src": "/photos/shreya/SCRL_0082.jpg",
    "alt": "SCRL 0082",
    "collection": "shreya",
    "featured": false
  },
  {
    "id": "tiana/original 2026-04-28 145829A877D6F97BB8.JPG",
    "src": "/photos/tiana/original%202026-04-28%20145829A877D6F97BB8.JPG",
    "alt": "original 2026 04 28 145829A877D6F97BB8",
    "collection": "tiana",
    "featured": false
  },
  {
    "id": "tiana/original 2026-04-28 1458450F5EA9FE5AD3.JPG",
    "src": "/photos/tiana/original%202026-04-28%201458450F5EA9FE5AD3.JPG",
    "alt": "original 2026 04 28 1458450F5EA9FE5AD3",
    "collection": "tiana",
    "featured": false
  },
  {
    "id": "tiana/original 2026-04-28 145848050C42600E44.JPG",
    "src": "/photos/tiana/original%202026-04-28%20145848050C42600E44.JPG",
    "alt": "original 2026 04 28 145848050C42600E44",
    "collection": "tiana",
    "featured": false
  },
  {
    "id": "tiana/original 2026-04-28 1458495018837CBBB9.JPG",
    "src": "/photos/tiana/original%202026-04-28%201458495018837CBBB9.JPG",
    "alt": "original 2026 04 28 1458495018837CBBB9",
    "collection": "tiana",
    "featured": false
  },
  {
    "id": "tiana/original 2026-04-28 14590539922D3FF6C9.JPG",
    "src": "/photos/tiana/original%202026-04-28%2014590539922D3FF6C9.JPG",
    "alt": "original 2026 04 28 14590539922D3FF6C9",
    "collection": "tiana",
    "featured": false
  },
  {
    "id": "tiana/original 2026-04-28 1459066E44B241DCD8.JPG",
    "src": "/photos/tiana/original%202026-04-28%201459066E44B241DCD8.JPG",
    "alt": "original 2026 04 28 1459066E44B241DCD8",
    "collection": "tiana",
    "featured": false
  },
  {
    "id": "tiana/original 2026-04-28 145915AD08D5F48F43.JPG",
    "src": "/photos/tiana/original%202026-04-28%20145915AD08D5F48F43.JPG",
    "alt": "original 2026 04 28 145915AD08D5F48F43",
    "collection": "tiana",
    "featured": false
  },
  {
    "id": "tiana/original 2026-04-28 145916EF3DECE95CD3.JPG",
    "src": "/photos/tiana/original%202026-04-28%20145916EF3DECE95CD3.JPG",
    "alt": "original 2026 04 28 145916EF3DECE95CD3",
    "collection": "tiana",
    "featured": false
  },
  {
    "id": "tiana/original 2026-04-28 1459183130B782CEC5.JPG",
    "src": "/photos/tiana/original%202026-04-28%201459183130B782CEC5.JPG",
    "alt": "original 2026 04 28 1459183130B782CEC5",
    "collection": "tiana",
    "featured": false
  },
  {
    "id": "tiana/original 2026-04-28 14592082B001FD61D1.JPG",
    "src": "/photos/tiana/original%202026-04-28%2014592082B001FD61D1.JPG",
    "alt": "original 2026 04 28 14592082B001FD61D1",
    "collection": "tiana",
    "featured": false
  },
  {
    "id": "tiana/original 2026-04-28 145920F470E86745AA.JPG",
    "src": "/photos/tiana/original%202026-04-28%20145920F470E86745AA.JPG",
    "alt": "original 2026 04 28 145920F470E86745AA",
    "collection": "tiana",
    "featured": false
  },
  {
    "id": "tiana/original 2026-04-28 1459219AC468E7B349.JPG",
    "src": "/photos/tiana/original%202026-04-28%201459219AC468E7B349.JPG",
    "alt": "original 2026 04 28 1459219AC468E7B349",
    "collection": "tiana",
    "featured": false
  },
  {
    "id": "tiana/original 2026-04-28 1459293A5B50EE27F4.JPG",
    "src": "/photos/tiana/original%202026-04-28%201459293A5B50EE27F4.JPG",
    "alt": "original 2026 04 28 1459293A5B50EE27F4",
    "collection": "tiana",
    "featured": false
  },
  {
    "id": "tiana/original 2026-04-28 145930154E789682C6.JPG",
    "src": "/photos/tiana/original%202026-04-28%20145930154E789682C6.JPG",
    "alt": "original 2026 04 28 145930154E789682C6",
    "collection": "tiana",
    "featured": false
  },
  {
    "id": "tiana/original 2026-04-28 14593170F1BB8950AD.jpg",
    "src": "/photos/tiana/original%202026-04-28%2014593170F1BB8950AD.jpg",
    "alt": "original 2026 04 28 14593170F1BB8950AD",
    "collection": "tiana",
    "featured": false
  },
  {
    "id": "tiana/original 2026-04-28 145935AC3CE26A3E54.JPG",
    "src": "/photos/tiana/original%202026-04-28%20145935AC3CE26A3E54.JPG",
    "alt": "original 2026 04 28 145935AC3CE26A3E54",
    "collection": "tiana",
    "featured": false
  },
  {
    "id": "tiana/original 2026-04-28 1459465D3A2FDA679F.JPG",
    "src": "/photos/tiana/original%202026-04-28%201459465D3A2FDA679F.JPG",
    "alt": "original 2026 04 28 1459465D3A2FDA679F",
    "collection": "tiana",
    "featured": false
  },
  {
    "id": "tiana/original 2026-04-28 1459475AAFB72205F2.JPG",
    "src": "/photos/tiana/original%202026-04-28%201459475AAFB72205F2.JPG",
    "alt": "original 2026 04 28 1459475AAFB72205F2",
    "collection": "tiana",
    "featured": false
  },
  {
    "id": "tiana/original 2026-04-28 1459495DFFC176F603.JPG",
    "src": "/photos/tiana/original%202026-04-28%201459495DFFC176F603.JPG",
    "alt": "original 2026 04 28 1459495DFFC176F603",
    "collection": "tiana",
    "featured": false
  },
  {
    "id": "tiana/original 2026-04-28 14595711CED4DF8C45.JPG",
    "src": "/photos/tiana/original%202026-04-28%2014595711CED4DF8C45.JPG",
    "alt": "original 2026 04 28 14595711CED4DF8C45",
    "collection": "tiana",
    "featured": false
  },
  {
    "id": "tiana/original 2026-04-28 1500006C0112EE821D.JPG",
    "src": "/photos/tiana/original%202026-04-28%201500006C0112EE821D.JPG",
    "alt": "original 2026 04 28 1500006C0112EE821D",
    "collection": "tiana",
    "featured": false
  },
  {
    "id": "tiana/original 2026-04-28 15000357CBAAA8BE86.JPG",
    "src": "/photos/tiana/original%202026-04-28%2015000357CBAAA8BE86.JPG",
    "alt": "original 2026 04 28 15000357CBAAA8BE86",
    "collection": "tiana",
    "featured": false
  },
  {
    "id": "tiana/original 2026-04-28 1500042DC1561FFD37.JPG",
    "src": "/photos/tiana/original%202026-04-28%201500042DC1561FFD37.JPG",
    "alt": "original 2026 04 28 1500042DC1561FFD37",
    "collection": "tiana",
    "featured": false
  },
  {
    "id": "tiana/original 2026-04-28 15000574066BF0EFFA.JPG",
    "src": "/photos/tiana/original%202026-04-28%2015000574066BF0EFFA.JPG",
    "alt": "original 2026 04 28 15000574066BF0EFFA",
    "collection": "tiana",
    "featured": false
  }
]
